version: '2'
services:
  datashare:
    image: icij/datashare:${VERSION}
    restart: on-failure
    environment:
      - "DS_JAVA_OPTS=\${DS_JAVA_OPTS}"
      - "DS_DOCKER_MOUNTED_DATA_DIR=\${APPDATA}/Datashare/data"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "\${APPDATA}/Datashare/models:/home/datashare/dist"
      - "\${APPDATA}/Datashare/data:/home/datashare/data:ro"

  redis:
    image: redis:4.0.1-alpine
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    restart: on-failure
    environment:
      - "ES_JAVA_OPTS=\${DS_JAVA_OPTS}"
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "cluster.name=datashare"
      - "discovery.type=single-node"
      - "discovery.zen.minimum_master_nodes=1"
      - "xpack.license.self_generated.type=basic"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
