version: '2.1'
services:
  datashare:
    image: icij/datashare:${VERSION}
    restart: on-failure
    environment:
      - "DS_JAVA_OPTS=\${DS_JAVA_OPTS}"
      - "DS_DOCKER_MOUNTED_DATA_DIR=\${APPDATA}/Datashare/data"
    command: --dataSourceUrl jdbc:sqlite:/home/datashare/dist/database.sqlite --pluginsDir /home/datashare/plugins --extensionsDir /home/datashare/extensions
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "\${APPDATA}/Datashare/dist:/home/datashare/dist"
      - "\${APPDATA}/Datashare/data:/home/datashare/data:ro"
      - "\${APPDATA}/Datashare/plugins:/home/datashare/plugins"
      - "\${APPDATA}/Datashare/extensions:/home/datashare/extensions"

  redis:
    image: redis:4.0.1-alpine
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    restart: on-failure
    volumes:
      - "\${APPDATA}/Datashare/index:/usr/share/elasticsearch/data"
    environment:
      - "ES_JAVA_OPTS=\${DS_JAVA_OPTS}"
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "cluster.name=datashare"
      - "discovery.type=single-node"
      - "discovery.zen.minimum_master_nodes=1"
      - "xpack.license.self_generated.type=basic"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
