version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:1.77.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-dependencies
      - run:
          name: install dependencies
          command: |
            sudo apt-get update && sudo apt install -y nsis cpio jq imagemagick icnsutils libxml2-dev
            wget https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip && unzip Inetc.zip && sudo cp Plugins/x86-unicode/INetC.dll /usr/share/nsis/Plugins/x86-unicode/ && echo "cp INetC.dll done"
            wget https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip && unzip EnVar_plugin.zip && sudo cp Plugins/x86-unicode/EnVar.dll /usr/share/nsis/Plugins/x86-unicode && echo "cp EnVar.dll done"
            wget https://github.com/ICIJ/bomutils/archive/refs/heads/master.zip && unzip master.zip && cd bomutils-master && make && sudo make install
            wget https://github.com/mackyle/xar/archive/refs/tags/xar-1.6.1.tar.gz && tar -zxf xar-1.6.1.tar.gz && cd xar-xar-1.6.1/xar && sed -i 's/OpenSSL_add_all_ciphers/OPENSSL_init_crypto/g' configure.ac && ./autogen.sh && make && sudo make install
            wget https://nsis.sourceforge.io/mediawiki/images/9/9d/Untgz.zip  && unzip Untgz.zip && sudo cp untgz/untgz.dll /usr/share/nsis/Plugins/ && echo "cp untgz.dll done"
            cargo install apple-codesign
      - save_cache:
          key: cargo-dependencies
          paths:
            - /home/circleci/.cargo
      - run:
          name: make windows
          command: |
            cd windows
            # The version here does not matter
            make VERSION=10.15.0 all
            cd ..
      - run:
          name: make linux
          command: |
            cd linux
            # The version here does not matter
            make VERSION=10.15.0 all
            cd ..