version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:1.77.1

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get update && sudo apt install -y nsis cpio jq imagemagick icnsutils
            wget https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip && unzip Inetc.zip && sudo cp Plugins/x86-unicode/INetC.dll /usr/share/nsis/Plugins/x86-unicode/ && echo "cp INetC.dll done"
            wget https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip && unzip EnVar_plugin.zip && sudo cp Plugins/x86-unicode/EnVar.dll /usr/share/nsis/Plugins/x86-unicode && echo "cp EnVar.dll done"
            wget https://github.com/hogliux/bomutils/archive/0.2.tar.gz && tar -zxf 0.2.tar.gz && cd bomutils-0.2 && make && sudo make install
            wget https://github.com/mackyle/xar/archive/refs/tags/xar-1.6.1.tar.gz && tar -zxf xar-1.6.1.tar.gz && cd xar-xar-1.6.1/xar && ./autogen.sh && make && sudo make install
            wget https://nsis.sourceforge.io/mediawiki/images/9/9d/Untgz.zip  && unzip Untgz.zip && sudo cp untgz/untgz.dll /usr/share/nsis/Plugins/ && echo "cp untgz.dll done"
            sudo cargo install apple-codesign

      - run:
          name: make windows
          command: |
            cd windows
            # The version here does not matter
            make VERSION=10.15.0 all
            cd ..

      - run:
          name: make linux
          command: |
            cd linux
            # The version here does not matter
            make VERSION=10.15.0 all
            cd ..

      - run:
          name: make mac
          command: |
            cd /tmp/datashare-installer/mac
            make VERSION=10.15.0 all