#!/bin/bash

echo "post-install"

DS_VERSION=__version__

# install Datashare backend
if [ -f /Applications/Datashare.app/Contents/Resources/datashare-dist-${DS_VERSION}.jar ]; then
  echo "datashare backend is already downloaded"
else
  echo "downloading datashare backend"
  curl -L -o /Applications/Datashare.app/Contents/Resources/datashare-dist-${DS_VERSION}.jar \
    https://github.com/ICIJ/datashare/releases/download/${DS_VERSION}/datashare-dist-${DS_VERSION}.jar
fi

# install Datashare frontend
echo "downloading datashare frontend"
curl -L -o /tmp/datashare-client-${DS_VERSION}.tgz https://github.com/ICIJ/datashare-client/releases/download/${DS_VERSION}/datashare-client-${DS_VERSION}.tgz
mkdir -p "/Applications/Datashare.app/Contents/Resources/app"
tar xzf /tmp/datashare-client-${DS_VERSION}.tgz --directory /Applications/Datashare.app/Contents/Resources/app

# create user folders
mkdir -p "${HOME}/Datashare"
mkdir -p "/Users/${USER}/Library/Datashare/dist"
mkdir -p "/Users/${USER}/Library/Datashare/index"
ln -s "/Applications/Datashare.app/Contents/Resources/app" "/Users/${USER}/Library/Datashare/app"
chown -R "${USER}:staff" "${HOME}/Datashare"
chown -R "${USER}:staff" "/Users/${USER}/Library/Datashare"
