#!/bin/bash

echo "post-install"

DS_VERSION=__version__

# install Datashare
if [ -f /Applications/Datashare.app/Contents/Resources/datashare-dist-${DS_VERSION}-all.jar ]; then
  echo "datashare backend is already downloaded"
else
  echo "downloading datashare backend"
  curl -L -o /Applications/Datashare.app/Contents/Resources/datashare-dist-${DS_VERSION}-all.jar \
    https://github.com/ICIJ/datashare/releases/download/${DS_VERSION}/datashare-dist-${DS_VERSION}-all.jar
fi

# create user folders
mkdir -p "${HOME}/Datashare"
mkdir -p "/Users/${USER}/Library/Datashare/dist"
mkdir -p "/Users/${USER}/Library/Datashare/index"
chown -R "${USER}:staff" "${HOME}/Datashare"
chown -R "${USER}:staff" "/Users/${USER}/Library/Datashare"
