#!/bin/bash

ds_version=__version__
ds_jar=datashare-dist-$ds_version-all.jar
ds_jar_dir=/Applications/Datashare.app/Contents/Resources
ds_jar_path=$ds_jar_dir/$ds_jar
ds_jar_url=https://github.com/ICIJ/datashare/releases/download/$ds_version/$ds_jar
elasticsearch_version=8.19.8
datashare_home="$HOME/Library/Datashare"
es_home="$datashare_home/elasticsearch"
es_setup_script="/Applications/Datashare.app/Contents/MacOS/elasticsearch-setup.sh"

log_error () {
  # This function takes a single argument, which is the message to log.
  # The logger command is used to log the message to the install facility
  # at the error level.
  logger -t DatashareInstaller -p install.error "$1"
}

log_info () {
  # This function takes a single argument, which is the message to log.
  # The logger command is used to log the message to the install facility
  # at the info level.
  logger -t DatashareInstaller -p install.info "$1"
}

is_datashare_installed () {
  # Datashare Jar was not found
  if ! [ -f $ds_jar_path ]; then
    return 1
  fi

  log_info "Datashare $ds_version is already installed."
}

create_datashare_cli () {
    if ! command -v datashare 1>/dev/null 2>&1 ; then
        sudo ln -s /Applications/Datashare.app/Contents/MacOS/Datashare.command /usr/local/bin/datashare
        if [ $? -ne 0 ]; then
            log_error "Unable to create Datashare CLI"
            # TODO: uncomment this to exit here in case of failure
#            return 1
        else
            log_info 'Successfully create datashare CLI'
        fi
    fi
}

download_datashare () {
  log_info "Downloading Datashare to: $ds_jar_path"
  mkdir -p $ds_jar_dir
  rm -f $ds_jar_path
  curl -s --fail -L $ds_jar_url -o $ds_jar_path
  # If curl returns an exit code different than 0, the download failed
  if [ $? -ne 0 ]; then
    log_error "Unable to download Datashare from: $ds_jar_url"
    return 1
  fi
  log_info 'Successfully installed Datashare.'
}

is_elasticsearch_installed () {
  # Check if Elasticsearch is already installed
  if [ -d "$es_home/elasticsearch-$elasticsearch_version" ]; then
    return 0
  fi
  return 1
}

download_elasticsearch () {
  log_info "Downloading Elasticsearch..."
  if [ -f "$es_setup_script" ]; then
    DATASHARE_HOME="$datashare_home" bash "$es_setup_script" install
    if [ $? -eq 0 ]; then
      log_info "Successfully installed Elasticsearch."
    else
      log_error "Failed to install Elasticsearch."
      return 1
    fi
  else
    log_error "Elasticsearch setup script not found at: $es_setup_script"
    return 1
  fi
}


setup_user_directories () {
  mkdir -p "$HOME/Datashare"
  mkdir -p "$datashare_home/dist"
  mkdir -p "$datashare_home/index"
  mkdir -p "$es_home"
  chown -R "$USER:staff" "$HOME/Datashare"
  chown -R "$USER:staff" "$datashare_home"
}

# Download Datashare, regardless of the current installation.
# If the download doesnt success, we exit the script.
if ! is_datashare_installed && ! download_datashare ; then
  log_error 'The installation cannot be done.'
  exit 1
fi
# Setup user directories
setup_user_directories
# Download Elasticsearch if not already installed
if ! is_elasticsearch_installed && ! download_elasticsearch ; then
  log_error 'Elasticsearch installation failed.'
  exit 1
fi
# When everything is done, we create the datashare CLI if it doesn't exist yet
create_datashare_cli
