#!/bin/bash

echo "pre-install"

DOCKER_URL=https://download.docker.com/mac/stable/Docker.dmg

if [ -d "/Applications/Docker.app" ]; then
  echo "Nice, Docker is installed"
else
  curl -O ${DOCKER_URL}
  echo "downloaded docker (res: $?)"
  hdiutil attach -nobrowse Docker.dmg
  echo "mounted Docker volume (res: $?)"
  cp -a /Volumes/Docker/Docker.app /Applications/
  echo "cp docker app (res: $?)"
  sync
  hdiutil detach /Volumes/Docker
  echo "unmounted docker volume (res: $?)"
fi
