#!/bin/bash

echo "pre-install"

JAVA_PKG=OpenJDK8U-jre_x64_mac_hotspot_8u242b08.pkg

echo "path : $PATH"
PATH_WITH_SPACES=$(echo $PATH | sed 's/:/ /g')
BREW_PATHS="/usr/local/bin /opt/homebrew/bin $PATH_WITH_SPACES"
BREW=""
echo "searching brew in : $BREW_PATHS"
for path in $BREW_PATHS
do
  if [[ -x "$path/brew" ]]; then
    BREW="$path/brew"
  fi
done
command -v "$BREW"  || { echo >&2 "I require brew but it's not installed. Aborting."; exit 1; }

# install tesseractOCR
if command /usr/local/bin/tesseract 2>/dev/null; then
  echo "tesseractOCR is installed"
else
  /usr/bin/sudo -i -u "${USER}" "$BREW" install imagemagick
  /usr/bin/sudo -i -u "${USER}" "$BREW" install leptonica
  /usr/bin/sudo -i -u "${USER}" "$BREW" install tesseract
  /usr/bin/sudo -i -u "${USER}" "$BREW" install tesseract-lang
fi

# install JRE
if [ -d /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jre ]; then
  echo "$JAVA_PKG is installed"
else
  curl -L -o /tmp/$JAVA_PKG https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/$JAVA_PKG
  installer -pkg /tmp/$JAVA_PKG -target /
fi
