#!/bin/bash

echo "pre-install"

DOCKER_URL=https://download.docker.com/mac/stable/Docker.dmg

if [ -d "/Applications/Docker.app" ]; then
  echo "Nice, Docker is installed"
else
  curl -O ${DOCKER_URL}
  hdiutil attach -nobrowse Docker.dmg
  cp -a /Volumes/Docker/Docker.app /Applications/
  hdiutils detach /Volumes/Docker
fi